/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSkillRouteImport } from './routes/_layout/skill'
import { Route as LayoutProjectsRouteImport } from './routes/_layout/projects'
import { Route as LayoutLoginRouteImport } from './routes/_layout/login'
import { Route as LayoutIronclawRouteImport } from './routes/_layout/ironclaw'
import { Route as LayoutEventsRouteImport } from './routes/_layout/events'
import { Route as LayoutAboutRouteImport } from './routes/_layout/about'
import { Route as LayoutAuthenticatedRouteImport } from './routes/_layout/_authenticated'
import { Route as LayoutAdminRouteImport } from './routes/_layout/_admin'
import { Route as LayoutProjectsIndexRouteImport } from './routes/_layout/projects/index'
import { Route as LayoutBuildersIndexRouteImport } from './routes/_layout/builders/index'
import { Route as LayoutAppsIndexRouteImport } from './routes/_layout/apps/index'
import { Route as LayoutProjectsNewRouteImport } from './routes/_layout/projects/new'
import { Route as LayoutProjectsIdRouteImport } from './routes/_layout/projects/$id'
import { Route as LayoutEventsIndexRouteImport } from './routes/_layout/events/index'
import { Route as LayoutBuildersIndexRouteImport } from './routes/_layout/builders/index'
import { Route as LayoutAppsIndexRouteImport } from './routes/_layout/apps/index'
import { Route as LayoutEventsNewRouteImport } from './routes/_layout/events/new'
import { Route as LayoutEventsIdRouteImport } from './routes/_layout/events/$id'
import { Route as LayoutBuildersAddRouteImport } from './routes/_layout/builders/add'
import { Route as LayoutBuildersAccountRouteImport } from './routes/_layout/builders/$account'
import { Route as LayoutAuthenticatedDashboardRouteImport } from './routes/_layout/_authenticated/_dashboard'
import { Route as LayoutAdminDashboardRouteImport } from './routes/_layout/_admin/dashboard'
import { Route as LayoutAppsAccountIdIndexRouteImport } from './routes/_layout/apps/$accountId/index'
import { Route as LayoutProjectsIdEditRouteImport } from './routes/_layout/projects/$id_.edit'
import { Route as LayoutEventsIdEditRouteImport } from './routes/_layout/events/$id_.edit'
import { Route as LayoutBuildersAccountEditRouteImport } from './routes/_layout/builders/$account_.edit'
import { Route as LayoutAppsAccountIdGatewayIdRouteImport } from './routes/_layout/apps/$accountId/$gatewayId'
import { Route as LayoutAuthenticatedAcceptInvitationIdRouteImport } from './routes/_layout/_authenticated/accept-invitation.$id'
import { Route as LayoutAuthenticatedDashboardSettingsRouteImport } from './routes/_layout/_authenticated/_dashboard/settings'
import { Route as LayoutAuthenticatedDashboardHomeRouteImport } from './routes/_layout/_authenticated/_dashboard/home'
import { Route as LayoutAuthenticatedDashboardSettingsIndexRouteImport } from './routes/_layout/_authenticated/_dashboard/settings/index'
import { Route as LayoutAuthenticatedDashboardOrganizationsIndexRouteImport } from './routes/_layout/_authenticated/_dashboard/organizations/index'
import { Route as LayoutAuthenticatedDashboardSettingsSecurityRouteImport } from './routes/_layout/_authenticated/_dashboard/settings/security'
import { Route as LayoutAuthenticatedDashboardSettingsProfileRouteImport } from './routes/_layout/_authenticated/_dashboard/settings/profile'
import { Route as LayoutAuthenticatedDashboardSettingsAuthMethodsRouteImport } from './routes/_layout/_authenticated/_dashboard/settings/auth-methods'
import { Route as LayoutAuthenticatedDashboardSettingsApiKeysRouteImport } from './routes/_layout/_authenticated/_dashboard/settings/api-keys'
import { Route as LayoutAuthenticatedDashboardOrganizationsNewRouteImport } from './routes/_layout/_authenticated/_dashboard/organizations/new'
import { Route as LayoutAuthenticatedDashboardOrganizationsSlugRouteImport } from './routes/_layout/_authenticated/_dashboard/organizations/$slug'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSkillRoute = LayoutSkillRouteImport.update({
  id: '/skill',
  path: '/skill',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProjectsRoute = LayoutProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLoginRoute = LayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutIronclawRoute = LayoutIronclawRouteImport.update({
  id: '/ironclaw',
  path: '/ironclaw',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEventsRoute = LayoutEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAboutRoute = LayoutAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAuthenticatedRoute = LayoutAuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProjectsIndexRoute = LayoutProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutProjectsRoute,
const LayoutEventsIndexRoute = LayoutEventsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutEventsRoute,
} as any)
const LayoutBuildersIndexRoute = LayoutBuildersIndexRouteImport.update({
  id: '/builders/',
  path: '/builders/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAppsIndexRoute = LayoutAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProjectsNewRoute = LayoutProjectsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => LayoutProjectsRoute,
} as any)
const LayoutProjectsIdRoute = LayoutProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LayoutProjectsRoute,
const LayoutEventsNewRoute = LayoutEventsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => LayoutEventsRoute,
} as any)
const LayoutEventsIdRoute = LayoutEventsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LayoutEventsRoute,
} as any)
const LayoutBuildersAddRoute = LayoutBuildersAddRouteImport.update({
  id: '/builders/add',
  path: '/builders/add',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBuildersAccountRoute = LayoutBuildersAccountRouteImport.update({
  id: '/builders/$account',
  path: '/builders/$account',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAuthenticatedDashboardRoute =
  LayoutAuthenticatedDashboardRouteImport.update({
    id: '/_dashboard',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAdminDashboardRoute = LayoutAdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAppsAccountIdIndexRoute =
  LayoutAppsAccountIdIndexRouteImport.update({
    id: '/apps/$accountId/',
    path: '/apps/$accountId/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutProjectsIdEditRoute = LayoutProjectsIdEditRouteImport.update({
  id: '/$id_/edit',
  path: '/$id/edit',
  getParentRoute: () => LayoutProjectsRoute,
const LayoutEventsIdEditRoute = LayoutEventsIdEditRouteImport.update({
  id: '/$id_/edit',
  path: '/$id/edit',
  getParentRoute: () => LayoutEventsRoute,
} as any)
const LayoutBuildersAccountEditRoute =
  LayoutBuildersAccountEditRouteImport.update({
    id: '/builders/$account_/edit',
    path: '/builders/$account/edit',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAppsAccountIdGatewayIdRoute =
  LayoutAppsAccountIdGatewayIdRouteImport.update({
    id: '/apps/$accountId/$gatewayId',
    path: '/apps/$accountId/$gatewayId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAuthenticatedAcceptInvitationIdRoute =
  LayoutAuthenticatedAcceptInvitationIdRouteImport.update({
    id: '/accept-invitation/$id',
    path: '/accept-invitation/$id',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsRoute =
  LayoutAuthenticatedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => LayoutAuthenticatedDashboardRoute,
  } as any)
const LayoutAuthenticatedDashboardHomeRoute =
  LayoutAuthenticatedDashboardHomeRouteImport.update({
    id: '/home',
    path: '/home',
    getParentRoute: () => LayoutAuthenticatedDashboardRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsIndexRoute =
  LayoutAuthenticatedDashboardSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsRoute,
  } as any)
const LayoutAuthenticatedDashboardOrganizationsIndexRoute =
  LayoutAuthenticatedDashboardOrganizationsIndexRouteImport.update({
    id: '/organizations/',
    path: '/organizations/',
    getParentRoute: () => LayoutAuthenticatedDashboardRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsSecurityRoute =
  LayoutAuthenticatedDashboardSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsProfileRoute =
  LayoutAuthenticatedDashboardSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsAuthMethodsRoute =
  LayoutAuthenticatedDashboardSettingsAuthMethodsRouteImport.update({
    id: '/auth-methods',
    path: '/auth-methods',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsApiKeysRoute =
  LayoutAuthenticatedDashboardSettingsApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsRoute,
  } as any)
const LayoutAuthenticatedDashboardOrganizationsNewRoute =
  LayoutAuthenticatedDashboardOrganizationsNewRouteImport.update({
    id: '/organizations/new',
    path: '/organizations/new',
    getParentRoute: () => LayoutAuthenticatedDashboardRoute,
  } as any)
const LayoutAuthenticatedDashboardOrganizationsSlugRoute =
  LayoutAuthenticatedDashboardOrganizationsSlugRouteImport.update({
    id: '/organizations/$slug',
    path: '/organizations/$slug',
    getParentRoute: () => LayoutAuthenticatedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/about': typeof LayoutAboutRoute
  '/events': typeof LayoutEventsRouteWithChildren
  '/ironclaw': typeof LayoutIronclawRoute
  '/login': typeof LayoutLoginRoute
  '/projects': typeof LayoutProjectsRouteWithChildren
  '/skill': typeof LayoutSkillRoute
  '/dashboard': typeof LayoutAdminDashboardRoute
  '/builders/$account': typeof LayoutBuildersAccountRoute
  '/builders/add': typeof LayoutBuildersAddRoute
  '/projects/$id': typeof LayoutProjectsIdRoute
  '/projects/new': typeof LayoutProjectsNewRoute
  '/apps/': typeof LayoutAppsIndexRoute
  '/builders/': typeof LayoutBuildersIndexRoute
  '/projects/': typeof LayoutProjectsIndexRoute
  '/events/$id': typeof LayoutEventsIdRoute
  '/events/new': typeof LayoutEventsNewRoute
  '/apps/': typeof LayoutAppsIndexRoute
  '/builders/': typeof LayoutBuildersIndexRoute
  '/events/': typeof LayoutEventsIndexRoute
  '/home': typeof LayoutAuthenticatedDashboardHomeRoute
  '/settings': typeof LayoutAuthenticatedDashboardSettingsRouteWithChildren
  '/accept-invitation/$id': typeof LayoutAuthenticatedAcceptInvitationIdRoute
  '/apps/$accountId/$gatewayId': typeof LayoutAppsAccountIdGatewayIdRoute
  '/builders/$account/edit': typeof LayoutBuildersAccountEditRoute
  '/projects/$id/edit': typeof LayoutProjectsIdEditRoute
  '/events/$id/edit': typeof LayoutEventsIdEditRoute
  '/apps/$accountId/': typeof LayoutAppsAccountIdIndexRoute
  '/organizations/$slug': typeof LayoutAuthenticatedDashboardOrganizationsSlugRoute
  '/organizations/new': typeof LayoutAuthenticatedDashboardOrganizationsNewRoute
  '/settings/api-keys': typeof LayoutAuthenticatedDashboardSettingsApiKeysRoute
  '/settings/auth-methods': typeof LayoutAuthenticatedDashboardSettingsAuthMethodsRoute
  '/settings/profile': typeof LayoutAuthenticatedDashboardSettingsProfileRoute
  '/settings/security': typeof LayoutAuthenticatedDashboardSettingsSecurityRoute
  '/organizations/': typeof LayoutAuthenticatedDashboardOrganizationsIndexRoute
  '/settings/': typeof LayoutAuthenticatedDashboardSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof LayoutIndexRoute
  '/about': typeof LayoutAboutRoute
  '/ironclaw': typeof LayoutIronclawRoute
  '/login': typeof LayoutLoginRoute
  '/skill': typeof LayoutSkillRoute
  '/dashboard': typeof LayoutAdminDashboardRoute
  '/builders/$account': typeof LayoutBuildersAccountRoute
  '/builders/add': typeof LayoutBuildersAddRoute
  '/projects/$id': typeof LayoutProjectsIdRoute
  '/projects/new': typeof LayoutProjectsNewRoute
  '/apps': typeof LayoutAppsIndexRoute
  '/builders': typeof LayoutBuildersIndexRoute
  '/projects': typeof LayoutProjectsIndexRoute
  '/events/$id': typeof LayoutEventsIdRoute
  '/events/new': typeof LayoutEventsNewRoute
  '/apps': typeof LayoutAppsIndexRoute
  '/builders': typeof LayoutBuildersIndexRoute
  '/events': typeof LayoutEventsIndexRoute
  '/home': typeof LayoutAuthenticatedDashboardHomeRoute
  '/accept-invitation/$id': typeof LayoutAuthenticatedAcceptInvitationIdRoute
  '/apps/$accountId/$gatewayId': typeof LayoutAppsAccountIdGatewayIdRoute
  '/builders/$account/edit': typeof LayoutBuildersAccountEditRoute
  '/projects/$id/edit': typeof LayoutProjectsIdEditRoute
  '/events/$id/edit': typeof LayoutEventsIdEditRoute
  '/apps/$accountId': typeof LayoutAppsAccountIdIndexRoute
  '/organizations/$slug': typeof LayoutAuthenticatedDashboardOrganizationsSlugRoute
  '/organizations/new': typeof LayoutAuthenticatedDashboardOrganizationsNewRoute
  '/settings/api-keys': typeof LayoutAuthenticatedDashboardSettingsApiKeysRoute
  '/settings/auth-methods': typeof LayoutAuthenticatedDashboardSettingsAuthMethodsRoute
  '/settings/profile': typeof LayoutAuthenticatedDashboardSettingsProfileRoute
  '/settings/security': typeof LayoutAuthenticatedDashboardSettingsSecurityRoute
  '/organizations': typeof LayoutAuthenticatedDashboardOrganizationsIndexRoute
  '/settings': typeof LayoutAuthenticatedDashboardSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/_admin': typeof LayoutAdminRouteWithChildren
  '/_layout/_authenticated': typeof LayoutAuthenticatedRouteWithChildren
  '/_layout/about': typeof LayoutAboutRoute
  '/_layout/events': typeof LayoutEventsRouteWithChildren
  '/_layout/ironclaw': typeof LayoutIronclawRoute
  '/_layout/login': typeof LayoutLoginRoute
  '/_layout/projects': typeof LayoutProjectsRouteWithChildren
  '/_layout/skill': typeof LayoutSkillRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/_admin/dashboard': typeof LayoutAdminDashboardRoute
  '/_layout/_authenticated/_dashboard': typeof LayoutAuthenticatedDashboardRouteWithChildren
  '/_layout/builders/$account': typeof LayoutBuildersAccountRoute
  '/_layout/builders/add': typeof LayoutBuildersAddRoute
  '/_layout/projects/$id': typeof LayoutProjectsIdRoute
  '/_layout/projects/new': typeof LayoutProjectsNewRoute
  '/_layout/apps/': typeof LayoutAppsIndexRoute
  '/_layout/builders/': typeof LayoutBuildersIndexRoute
  '/_layout/projects/': typeof LayoutProjectsIndexRoute
  '/_layout/events/$id': typeof LayoutEventsIdRoute
  '/_layout/events/new': typeof LayoutEventsNewRoute
  '/_layout/apps/': typeof LayoutAppsIndexRoute
  '/_layout/builders/': typeof LayoutBuildersIndexRoute
  '/_layout/events/': typeof LayoutEventsIndexRoute
  '/_layout/_authenticated/_dashboard/home': typeof LayoutAuthenticatedDashboardHomeRoute
  '/_layout/_authenticated/_dashboard/settings': typeof LayoutAuthenticatedDashboardSettingsRouteWithChildren
  '/_layout/_authenticated/accept-invitation/$id': typeof LayoutAuthenticatedAcceptInvitationIdRoute
  '/_layout/apps/$accountId/$gatewayId': typeof LayoutAppsAccountIdGatewayIdRoute
  '/_layout/builders/$account_/edit': typeof LayoutBuildersAccountEditRoute
  '/_layout/projects/$id_/edit': typeof LayoutProjectsIdEditRoute
  '/_layout/events/$id_/edit': typeof LayoutEventsIdEditRoute
  '/_layout/apps/$accountId/': typeof LayoutAppsAccountIdIndexRoute
  '/_layout/_authenticated/_dashboard/organizations/$slug': typeof LayoutAuthenticatedDashboardOrganizationsSlugRoute
  '/_layout/_authenticated/_dashboard/organizations/new': typeof LayoutAuthenticatedDashboardOrganizationsNewRoute
  '/_layout/_authenticated/_dashboard/settings/api-keys': typeof LayoutAuthenticatedDashboardSettingsApiKeysRoute
  '/_layout/_authenticated/_dashboard/settings/auth-methods': typeof LayoutAuthenticatedDashboardSettingsAuthMethodsRoute
  '/_layout/_authenticated/_dashboard/settings/profile': typeof LayoutAuthenticatedDashboardSettingsProfileRoute
  '/_layout/_authenticated/_dashboard/settings/security': typeof LayoutAuthenticatedDashboardSettingsSecurityRoute
  '/_layout/_authenticated/_dashboard/organizations/': typeof LayoutAuthenticatedDashboardOrganizationsIndexRoute
  '/_layout/_authenticated/_dashboard/settings/': typeof LayoutAuthenticatedDashboardSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/events'
    | '/ironclaw'
    | '/login'
    | '/projects'
    | '/skill'
    | '/dashboard'
    | '/builders/$account'
    | '/builders/add'
    | '/projects/$id'
    | '/projects/new'
    | '/apps/'
    | '/builders/'
    | '/projects/'
    | '/events/$id'
    | '/events/new'
    | '/apps/'
    | '/builders/'
    | '/events/'
    | '/home'
    | '/settings'
    | '/accept-invitation/$id'
    | '/apps/$accountId/$gatewayId'
    | '/builders/$account/edit'
    | '/projects/$id/edit'
    | '/events/$id/edit'
    | '/apps/$accountId/'
    | '/organizations/$slug'
    | '/organizations/new'
    | '/settings/api-keys'
    | '/settings/auth-methods'
    | '/settings/profile'
    | '/settings/security'
    | '/organizations/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ironclaw'
    | '/login'
    | '/skill'
    | '/dashboard'
    | '/builders/$account'
    | '/builders/add'
    | '/projects/$id'
    | '/projects/new'
    | '/apps'
    | '/builders'
    | '/projects'
    | '/events/$id'
    | '/events/new'
    | '/apps'
    | '/builders'
    | '/events'
    | '/home'
    | '/accept-invitation/$id'
    | '/apps/$accountId/$gatewayId'
    | '/builders/$account/edit'
    | '/projects/$id/edit'
    | '/events/$id/edit'
    | '/apps/$accountId'
    | '/organizations/$slug'
    | '/organizations/new'
    | '/settings/api-keys'
    | '/settings/auth-methods'
    | '/settings/profile'
    | '/settings/security'
    | '/organizations'
    | '/settings'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/_admin'
    | '/_layout/_authenticated'
    | '/_layout/about'
    | '/_layout/events'
    | '/_layout/ironclaw'
    | '/_layout/login'
    | '/_layout/projects'
    | '/_layout/skill'
    | '/_layout/'
    | '/_layout/_admin/dashboard'
    | '/_layout/_authenticated/_dashboard'
    | '/_layout/builders/$account'
    | '/_layout/builders/add'
    | '/_layout/projects/$id'
    | '/_layout/projects/new'
    | '/_layout/apps/'
    | '/_layout/builders/'
    | '/_layout/projects/'
    | '/_layout/events/$id'
    | '/_layout/events/new'
    | '/_layout/apps/'
    | '/_layout/builders/'
    | '/_layout/events/'
    | '/_layout/_authenticated/_dashboard/home'
    | '/_layout/_authenticated/_dashboard/settings'
    | '/_layout/_authenticated/accept-invitation/$id'
    | '/_layout/apps/$accountId/$gatewayId'
    | '/_layout/builders/$account_/edit'
    | '/_layout/projects/$id_/edit'
    | '/_layout/events/$id_/edit'
    | '/_layout/apps/$accountId/'
    | '/_layout/_authenticated/_dashboard/organizations/$slug'
    | '/_layout/_authenticated/_dashboard/organizations/new'
    | '/_layout/_authenticated/_dashboard/settings/api-keys'
    | '/_layout/_authenticated/_dashboard/settings/auth-methods'
    | '/_layout/_authenticated/_dashboard/settings/profile'
    | '/_layout/_authenticated/_dashboard/settings/security'
    | '/_layout/_authenticated/_dashboard/organizations/'
    | '/_layout/_authenticated/_dashboard/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/skill': {
      id: '/_layout/skill'
      path: '/skill'
      fullPath: '/skill'
      preLoaderRoute: typeof LayoutSkillRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/projects': {
      id: '/_layout/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof LayoutProjectsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/login': {
      id: '/_layout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LayoutLoginRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/ironclaw': {
      id: '/_layout/ironclaw'
      path: '/ironclaw'
      fullPath: '/ironclaw'
      preLoaderRoute: typeof LayoutIronclawRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/events': {
      id: '/_layout/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof LayoutEventsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/about': {
      id: '/_layout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LayoutAboutRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_authenticated': {
      id: '/_layout/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutAuthenticatedRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_admin': {
      id: '/_layout/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/projects/': {
      id: '/_layout/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof LayoutProjectsIndexRouteImport
      parentRoute: typeof LayoutProjectsRoute
    '/_layout/events/': {
      id: '/_layout/events/'
      path: '/'
      fullPath: '/events/'
      preLoaderRoute: typeof LayoutEventsIndexRouteImport
      parentRoute: typeof LayoutEventsRoute
    }
    '/_layout/builders/': {
      id: '/_layout/builders/'
      path: '/builders'
      fullPath: '/builders/'
      preLoaderRoute: typeof LayoutBuildersIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/apps/': {
      id: '/_layout/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof LayoutAppsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/projects/new': {
      id: '/_layout/projects/new'
      path: '/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof LayoutProjectsNewRouteImport
      parentRoute: typeof LayoutProjectsRoute
    }
    '/_layout/projects/$id': {
      id: '/_layout/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof LayoutProjectsIdRouteImport
      parentRoute: typeof LayoutProjectsRoute
    '/_layout/events/new': {
      id: '/_layout/events/new'
      path: '/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof LayoutEventsNewRouteImport
      parentRoute: typeof LayoutEventsRoute
    }
    '/_layout/events/$id': {
      id: '/_layout/events/$id'
      path: '/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof LayoutEventsIdRouteImport
      parentRoute: typeof LayoutEventsRoute
    }
    '/_layout/builders/add': {
      id: '/_layout/builders/add'
      path: '/builders/add'
      fullPath: '/builders/add'
      preLoaderRoute: typeof LayoutBuildersAddRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/builders/$account': {
      id: '/_layout/builders/$account'
      path: '/builders/$account'
      fullPath: '/builders/$account'
      preLoaderRoute: typeof LayoutBuildersAccountRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_authenticated/_dashboard': {
      id: '/_layout/_authenticated/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_admin/dashboard': {
      id: '/_layout/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutAdminDashboardRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/apps/$accountId/': {
      id: '/_layout/apps/$accountId/'
      path: '/apps/$accountId'
      fullPath: '/apps/$accountId/'
      preLoaderRoute: typeof LayoutAppsAccountIdIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/projects/$id_/edit': {
      id: '/_layout/projects/$id_/edit'
      path: '/$id/edit'
      fullPath: '/projects/$id/edit'
      preLoaderRoute: typeof LayoutProjectsIdEditRouteImport
      parentRoute: typeof LayoutProjectsRoute
    '/_layout/events/$id_/edit': {
      id: '/_layout/events/$id_/edit'
      path: '/$id/edit'
      fullPath: '/events/$id/edit'
      preLoaderRoute: typeof LayoutEventsIdEditRouteImport
      parentRoute: typeof LayoutEventsRoute
    }
    '/_layout/builders/$account_/edit': {
      id: '/_layout/builders/$account_/edit'
      path: '/builders/$account/edit'
      fullPath: '/builders/$account/edit'
      preLoaderRoute: typeof LayoutBuildersAccountEditRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/apps/$accountId/$gatewayId': {
      id: '/_layout/apps/$accountId/$gatewayId'
      path: '/apps/$accountId/$gatewayId'
      fullPath: '/apps/$accountId/$gatewayId'
      preLoaderRoute: typeof LayoutAppsAccountIdGatewayIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_authenticated/accept-invitation/$id': {
      id: '/_layout/_authenticated/accept-invitation/$id'
      path: '/accept-invitation/$id'
      fullPath: '/accept-invitation/$id'
      preLoaderRoute: typeof LayoutAuthenticatedAcceptInvitationIdRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/_dashboard/settings': {
      id: '/_layout/_authenticated/_dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardRoute
    }
    '/_layout/_authenticated/_dashboard/home': {
      id: '/_layout/_authenticated/_dashboard/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardHomeRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardRoute
    }
    '/_layout/_authenticated/_dashboard/settings/': {
      id: '/_layout/_authenticated/_dashboard/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsRoute
    }
    '/_layout/_authenticated/_dashboard/organizations/': {
      id: '/_layout/_authenticated/_dashboard/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardOrganizationsIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardRoute
    }
    '/_layout/_authenticated/_dashboard/settings/security': {
      id: '/_layout/_authenticated/_dashboard/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsSecurityRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsRoute
    }
    '/_layout/_authenticated/_dashboard/settings/profile': {
      id: '/_layout/_authenticated/_dashboard/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsProfileRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsRoute
    }
    '/_layout/_authenticated/_dashboard/settings/auth-methods': {
      id: '/_layout/_authenticated/_dashboard/settings/auth-methods'
      path: '/auth-methods'
      fullPath: '/settings/auth-methods'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsAuthMethodsRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsRoute
    }
    '/_layout/_authenticated/_dashboard/settings/api-keys': {
      id: '/_layout/_authenticated/_dashboard/settings/api-keys'
      path: '/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsApiKeysRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsRoute
    }
    '/_layout/_authenticated/_dashboard/organizations/new': {
      id: '/_layout/_authenticated/_dashboard/organizations/new'
      path: '/organizations/new'
      fullPath: '/organizations/new'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardOrganizationsNewRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardRoute
    }
    '/_layout/_authenticated/_dashboard/organizations/$slug': {
      id: '/_layout/_authenticated/_dashboard/organizations/$slug'
      path: '/organizations/$slug'
      fullPath: '/organizations/$slug'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardOrganizationsSlugRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardRoute
    }
  }
}

interface LayoutAdminRouteChildren {
  LayoutAdminDashboardRoute: typeof LayoutAdminDashboardRoute
}

const LayoutAdminRouteChildren: LayoutAdminRouteChildren = {
  LayoutAdminDashboardRoute: LayoutAdminDashboardRoute,
}

const LayoutAdminRouteWithChildren = LayoutAdminRoute._addFileChildren(
  LayoutAdminRouteChildren,
)

interface LayoutAuthenticatedDashboardSettingsRouteChildren {
  LayoutAuthenticatedDashboardSettingsApiKeysRoute: typeof LayoutAuthenticatedDashboardSettingsApiKeysRoute
  LayoutAuthenticatedDashboardSettingsAuthMethodsRoute: typeof LayoutAuthenticatedDashboardSettingsAuthMethodsRoute
  LayoutAuthenticatedDashboardSettingsProfileRoute: typeof LayoutAuthenticatedDashboardSettingsProfileRoute
  LayoutAuthenticatedDashboardSettingsSecurityRoute: typeof LayoutAuthenticatedDashboardSettingsSecurityRoute
  LayoutAuthenticatedDashboardSettingsIndexRoute: typeof LayoutAuthenticatedDashboardSettingsIndexRoute
}

const LayoutAuthenticatedDashboardSettingsRouteChildren: LayoutAuthenticatedDashboardSettingsRouteChildren =
  {
    LayoutAuthenticatedDashboardSettingsApiKeysRoute:
      LayoutAuthenticatedDashboardSettingsApiKeysRoute,
    LayoutAuthenticatedDashboardSettingsAuthMethodsRoute:
      LayoutAuthenticatedDashboardSettingsAuthMethodsRoute,
    LayoutAuthenticatedDashboardSettingsProfileRoute:
      LayoutAuthenticatedDashboardSettingsProfileRoute,
    LayoutAuthenticatedDashboardSettingsSecurityRoute:
      LayoutAuthenticatedDashboardSettingsSecurityRoute,
    LayoutAuthenticatedDashboardSettingsIndexRoute:
      LayoutAuthenticatedDashboardSettingsIndexRoute,
  }

const LayoutAuthenticatedDashboardSettingsRouteWithChildren =
  LayoutAuthenticatedDashboardSettingsRoute._addFileChildren(
    LayoutAuthenticatedDashboardSettingsRouteChildren,
  )

interface LayoutAuthenticatedDashboardRouteChildren {
  LayoutAuthenticatedDashboardHomeRoute: typeof LayoutAuthenticatedDashboardHomeRoute
  LayoutAuthenticatedDashboardSettingsRoute: typeof LayoutAuthenticatedDashboardSettingsRouteWithChildren
  LayoutAuthenticatedDashboardOrganizationsSlugRoute: typeof LayoutAuthenticatedDashboardOrganizationsSlugRoute
  LayoutAuthenticatedDashboardOrganizationsNewRoute: typeof LayoutAuthenticatedDashboardOrganizationsNewRoute
  LayoutAuthenticatedDashboardOrganizationsIndexRoute: typeof LayoutAuthenticatedDashboardOrganizationsIndexRoute
}

const LayoutAuthenticatedDashboardRouteChildren: LayoutAuthenticatedDashboardRouteChildren =
  {
    LayoutAuthenticatedDashboardHomeRoute:
      LayoutAuthenticatedDashboardHomeRoute,
    LayoutAuthenticatedDashboardSettingsRoute:
      LayoutAuthenticatedDashboardSettingsRouteWithChildren,
    LayoutAuthenticatedDashboardOrganizationsSlugRoute:
      LayoutAuthenticatedDashboardOrganizationsSlugRoute,
    LayoutAuthenticatedDashboardOrganizationsNewRoute:
      LayoutAuthenticatedDashboardOrganizationsNewRoute,
    LayoutAuthenticatedDashboardOrganizationsIndexRoute:
      LayoutAuthenticatedDashboardOrganizationsIndexRoute,
  }

const LayoutAuthenticatedDashboardRouteWithChildren =
  LayoutAuthenticatedDashboardRoute._addFileChildren(
    LayoutAuthenticatedDashboardRouteChildren,
  )

interface LayoutAuthenticatedRouteChildren {
  LayoutAuthenticatedDashboardRoute: typeof LayoutAuthenticatedDashboardRouteWithChildren
  LayoutAuthenticatedAcceptInvitationIdRoute: typeof LayoutAuthenticatedAcceptInvitationIdRoute
}

const LayoutAuthenticatedRouteChildren: LayoutAuthenticatedRouteChildren = {
  LayoutAuthenticatedDashboardRoute:
    LayoutAuthenticatedDashboardRouteWithChildren,
  LayoutAuthenticatedAcceptInvitationIdRoute:
    LayoutAuthenticatedAcceptInvitationIdRoute,
}

const LayoutAuthenticatedRouteWithChildren =
  LayoutAuthenticatedRoute._addFileChildren(LayoutAuthenticatedRouteChildren)

interface LayoutProjectsRouteChildren {
  LayoutProjectsIdRoute: typeof LayoutProjectsIdRoute
  LayoutProjectsNewRoute: typeof LayoutProjectsNewRoute
  LayoutProjectsIndexRoute: typeof LayoutProjectsIndexRoute
  LayoutProjectsIdEditRoute: typeof LayoutProjectsIdEditRoute
}

const LayoutProjectsRouteChildren: LayoutProjectsRouteChildren = {
  LayoutProjectsIdRoute: LayoutProjectsIdRoute,
  LayoutProjectsNewRoute: LayoutProjectsNewRoute,
  LayoutProjectsIndexRoute: LayoutProjectsIndexRoute,
  LayoutProjectsIdEditRoute: LayoutProjectsIdEditRoute,
}

const LayoutProjectsRouteWithChildren = LayoutProjectsRoute._addFileChildren(
  LayoutProjectsRouteChildren,
interface LayoutEventsRouteChildren {
  LayoutEventsIdRoute: typeof LayoutEventsIdRoute
  LayoutEventsNewRoute: typeof LayoutEventsNewRoute
  LayoutEventsIndexRoute: typeof LayoutEventsIndexRoute
  LayoutEventsIdEditRoute: typeof LayoutEventsIdEditRoute
}

const LayoutEventsRouteChildren: LayoutEventsRouteChildren = {
  LayoutEventsIdRoute: LayoutEventsIdRoute,
  LayoutEventsNewRoute: LayoutEventsNewRoute,
  LayoutEventsIndexRoute: LayoutEventsIndexRoute,
  LayoutEventsIdEditRoute: LayoutEventsIdEditRoute,
}

const LayoutEventsRouteWithChildren = LayoutEventsRoute._addFileChildren(
  LayoutEventsRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRouteWithChildren
  LayoutAuthenticatedRoute: typeof LayoutAuthenticatedRouteWithChildren
  LayoutAboutRoute: typeof LayoutAboutRoute
  LayoutEventsRoute: typeof LayoutEventsRouteWithChildren
  LayoutIronclawRoute: typeof LayoutIronclawRoute
  LayoutLoginRoute: typeof LayoutLoginRoute
  LayoutProjectsRoute: typeof LayoutProjectsRouteWithChildren
  LayoutSkillRoute: typeof LayoutSkillRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutBuildersAccountRoute: typeof LayoutBuildersAccountRoute
  LayoutBuildersAddRoute: typeof LayoutBuildersAddRoute
  LayoutAppsIndexRoute: typeof LayoutAppsIndexRoute
  LayoutBuildersIndexRoute: typeof LayoutBuildersIndexRoute
  LayoutAppsAccountIdGatewayIdRoute: typeof LayoutAppsAccountIdGatewayIdRoute
  LayoutBuildersAccountEditRoute: typeof LayoutBuildersAccountEditRoute
  LayoutAppsAccountIdIndexRoute: typeof LayoutAppsAccountIdIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRouteWithChildren,
  LayoutAuthenticatedRoute: LayoutAuthenticatedRouteWithChildren,
  LayoutAboutRoute: LayoutAboutRoute,
  LayoutEventsRoute: LayoutEventsRouteWithChildren,
  LayoutIronclawRoute: LayoutIronclawRoute,
  LayoutLoginRoute: LayoutLoginRoute,
  LayoutProjectsRoute: LayoutProjectsRouteWithChildren,
  LayoutSkillRoute: LayoutSkillRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutBuildersAccountRoute: LayoutBuildersAccountRoute,
  LayoutBuildersAddRoute: LayoutBuildersAddRoute,
  LayoutAppsIndexRoute: LayoutAppsIndexRoute,
  LayoutBuildersIndexRoute: LayoutBuildersIndexRoute,
  LayoutAppsAccountIdGatewayIdRoute: LayoutAppsAccountIdGatewayIdRoute,
  LayoutBuildersAccountEditRoute: LayoutBuildersAccountEditRoute,
  LayoutAppsAccountIdIndexRoute: LayoutAppsAccountIdIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
