import { bigint, index, integer, pgTable, text, timestamp, uniqueIndex } from "drizzle-orm/pg-core";

export const builders = pgTable(
  "builders",
  {
    id: text("id").primaryKey(),
    nearAccount: text("near_account").notNull().unique(),
    userId: text("user_id"),
    name: text("name"),
    bio: text("bio"),
    skills: text("skills"),
    location: text("location"),
    links: text("links"),
    createdAt: timestamp("created_at").defaultNow(),
    updatedAt: timestamp("updated_at").defaultNow(),
  },
  (table) => [
    uniqueIndex("builders_near_account_idx").on(table.nearAccount),
    index("builders_user_id_idx").on(table.userId),
  ],
);

export const builderNominations = pgTable(
  "builder_nominations",
  {
    id: text("id").primaryKey(),
    source: text("source").notNull(),
    sourceNominationId: text("source_nomination_id").notNull(),
    sourcePostUrl: text("source_post_url"),
    sourcePostText: text("source_post_text"),
    sourcePostCreatedAt: timestamp("source_post_created_at"),
    conversationId: text("conversation_id"),
    replyToPostId: text("reply_to_post_id"),
    sourceNomineeTelegramId: bigint("source_nominee_telegram_id", { mode: "number" }),
    sourceNomineeUsernameNormalized: text("source_nominee_username_normalized"),
    sourceNomineeXId: text("source_nominee_x_id"),
    sourceNomineeXUsername: text("source_nominee_x_username"),
    nomineeTelegramId: bigint("nominee_telegram_id", { mode: "number" }),
    nomineeUsername: text("nominee_username"),
    nomineeXId: text("nominee_x_id"),
    nomineeXUsername: text("nominee_x_username"),
    unresolvedUsernameNormalized: text("unresolved_username_normalized"),
    nominatedByTelegramId: bigint("nominated_by_telegram_id", { mode: "number" }),
    telegramGroupId: bigint("telegram_group_id", { mode: "number" }),
    nominatorXId: text("nominator_x_id"),
    nominatorXUsername: text("nominator_x_username"),
    createdByApiKeyId: text("created_by_api_key_id").notNull(),
    tokenHash: text("token_hash"),
    canonicalNominationId: text("canonical_nomination_id"),
    engagementStatus: text("engagement_status").notNull().default("pending_contact"),
    replyUrl: text("reply_url"),
    contactedAt: timestamp("contacted_at"),
    rejectedAt: timestamp("rejected_at"),
    completedAt: timestamp("completed_at"),
    engagementUpdatedAt: timestamp("engagement_updated_at").notNull().defaultNow(),
    updatedBy: text("updated_by"),
    firstOpenedAt: timestamp("first_opened_at"),
    lastOpenedAt: timestamp("last_opened_at"),
    openCount: integer("open_count").notNull().default(0),
    createdAt: timestamp("created_at").notNull().defaultNow(),
    proposalId: text("proposal_id"),
    submittedNearAccount: text("submitted_near_account"),
    submittedUserId: text("submitted_user_id"),
    submittedAt: timestamp("submitted_at"),
  },
  (table) => [
    uniqueIndex("builder_nominations_source_unique").on(table.source, table.sourceNominationId),
    uniqueIndex("builder_nominations_token_hash_unique").on(table.tokenHash),
    uniqueIndex("builder_nominations_telegram_id_unique").on(table.nomineeTelegramId),
    uniqueIndex("builder_nominations_x_id_unique").on(table.nomineeXId),
    uniqueIndex("builder_nominations_unresolved_username_unique").on(
      table.unresolvedUsernameNormalized,
    ),
    index("builder_nominations_source_nominee_x_id_idx").on(table.sourceNomineeXId),
    index("builder_nominations_source_nominee_x_username_idx").on(table.sourceNomineeXUsername),
    index("builder_nominations_engagement_status_idx").on(table.engagementStatus),
    index("builder_nominations_canonical_idx").on(table.canonicalNominationId),
  ],
);

export const builderXIdentities = pgTable(
  "builder_x_identities",
  {
    id: text("id").primaryKey(),
    xUserId: text("x_user_id"),
    username: text("username").notNull(),
    usernameNormalized: text("username_normalized").notNull(),
    builderId: text("builder_id"),
    createdAt: timestamp("created_at").notNull().defaultNow(),
    updatedAt: timestamp("updated_at").notNull().defaultNow(),
  },
  (table) => [
    uniqueIndex("builder_x_identities_x_user_id_unique").on(table.xUserId),
    index("builder_x_identities_username_idx").on(table.usernameNormalized),
    index("builder_x_identities_builder_idx").on(table.builderId),
  ],
);
